---
install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.deb -o hugo.deb
  - sudo dpkg -i hugo.deb

script:
  - hugo

deploy:
  - provider: script
    script: "/bin/bash ${TRAVIS_BUILD_DIR}/deploy.sh"
    skip_cleanup: true
    on:
      branch: master
