---
install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.deb -o hugo.deb
  - sudo dpkg -i hugo.deb

script:
  - hugo

deploy:
  - provider: pages
    fqdn: weeee.dev
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: public/
    repo: weeeedev/weeeedev.github.io
    target_branch: master
    keep_history: true
    on:
      branch: master
